### ISSUE TITLE
社内案件管理kintoneについて気になる点(7/3)

### ISSUE THREAD

**Issue by amikobayashi1** [asnetjp/kintoneStudy#3]
現在までの実装やテストケース洗い出しをする中で気になった点をまとめました。

・担当者マスタのIDも自動採番プラグインを使った方が良いのではないか
・現在受注の場合はステータス更新を行うという仕様だが、失注の場合は反映させなくてよいのか
・受注したら見積管理から受注金額も更新できた方が良いのではないか
・営業さんが多く触るということだが、PCから使用するという前提で良いのか(外で触ることが多いのであればスマホから使うこともあるのか知りたい)
→kintoneモバイルで見る場合はイベントハンドラーが異なるためソースコードの修正が必要
・見積管理から受注→案件管理のステータスを受注に更新という流れだが、案件管理からステータス更新で受注になったときはどういう挙動をするのか

**Comment by tsuneyama0825** [comment]
・担当者マスタのIDも自動採番プラグインを使った方が良いのではないか  
⇒そうしましょう。仕様追加決定。

・現在受注の場合はステータス更新を行うという仕様だが、失注の場合は反映させなくてよいのか  
⇒そうですよね、そもそも見積管理にステータスがあるのが混乱するかな、と思いました。 
    NICE営業物語をみたら、見積管理は「受注」のチェックボックス1つだけでした。    

・受注したら見積管理から受注金額も更新できた方が良いのではないか  
⇒その方が便利だと思います。仕様追加検討。  

・営業さんが多く触るということだが、PCから使用するという前提で良いのか(外で触ることが多いのであればスマホから使うこともあるのか知りたい)
→kintoneモバイルで見る場合はイベントハンドラーが異なるためソースコードの修正が必要  
⇒要確認ですね。  

・見積管理から受注→案件管理のステータスを受注に更新という流れだが、案件管理からステータス更新で受注になったときはどういう挙動をするのか  
⇒現状は、ただ案件管理が受注になるだけですよね。どの見積で受注したかわからないから
どうしましょうかね。

**Comment by tsuneyama0825** [comment]
1～3について修正できていることを確認しました。
